[crawler]
interval_secs = 10
timeout_secs = 120
subject_code = "cs"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.0.0"

[prompts]
dir = "prompts"

[filter]
relevance_threshold = 85
eval_concurrency = 4

[[topics]]
name = "Agentic ai"
description = "对于多个Agent相互协作的Agentic AI系统中系统层面有关问题的研究，如系统延迟、系统架构设计等。"

[[topics]]
name = "RLHF/RLVF"
description = "大语言模型(LLM)的强化学习后训练(post-train)系统(RLHF/RLVF)中，系统层面性能优化方法的相关研究，包括对于系统延迟、吞吐量和计算资源利用率等方面的优化。"

[ai]

[ai.models."deepseek-chat"]
provider = "deepseek"
endpoint = "https://api.deepseek.com/chat/completions"
system_prompt = "You are a helpful assistant"
timeout_secs = 60

[ai.models."deepseek-chat".request]
model = "deepseek-chat"
thinking_type = "disabled"
frequency_penalty = 0.0
max_tokens = 4096
presence_penalty = 0.0
response_format_type = "text"
stream = false
temperature = 1.0
top_p = 1.0
tool_choice = "none"
logprobs = false

[ai.models."deepseek-reasoner"]
provider = "deepseek"
endpoint = "https://api.deepseek.com/chat/completions"
system_prompt = "You are a helpful assistant"
timeout_secs = 300

[ai.models."deepseek-reasoner".request]
model = "deepseek-reasoner"
thinking_type = "enabled"
frequency_penalty = 0.0
max_tokens = 32768
presence_penalty = 0.0
response_format_type = "text"
stream = false
temperature = 1.0
top_p = 1.0
tool_choice = "none"
logprobs = false
